import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,migrateV2ToV3,migrateV3ToV4,validateState,SCHEMA_VERSION} from '../src/v3/schema.js';
import {HealthRepository,verifyBackupChecksum} from '../src/v3/storage.js';
import {findAnalyte,convertValue,normalizeResult,labStatus} from '../src/v3/labs.js';
import {parseCsv,parseLabText,validateUpload} from '../src/v3/importers.js';
import {encryptBackup,decryptBackup} from '../src/v3/crypto.js';
import {analyze,getTopRecommendations} from '../src/engine/recommendation-engine.js';
import {scoreBigFive,deriveArchetype} from '../src/modules/personality.js';

globalThis.MarkovHealthCatalog={catalog:[{id:'glucose',canonicalRu:'Глюкоза',shortRu:'Глюкоза',englishName:'Glucose',abbreviations:['GLU'],russianAliases:['сахар крови'],allowedUnits:['ммоль/л','mg/dL'],canonicalUnit:'ммоль/л',unitConversions:{'мг/дл->ммоль/л':v=>v/18.0182},category:'Углеводный обмен'},{id:'tsh',canonicalRu:'Тиреотропный гормон',shortRu:'ТТГ',englishName:'TSH',abbreviations:['TSH'],russianAliases:['тиреотропный гормон'],allowedUnits:['мМЕ/л'],canonicalUnit:'мМЕ/л',unitConversions:{},category:'Щитовидная железа'}]};

class MemoryStorage{constructor(seed={}){this.map=new Map(Object.entries(seed));}getItem(k){return this.map.has(k)?this.map.get(k):null;}setItem(k,v){this.map.set(k,String(v));}removeItem(k){this.map.delete(k);}}
function legacy(){return {version:2,activeProfileId:'p1',profiles:[{id:'p1',name:'P'}],measurements:[{id:'m1',profileId:'p1',type:'weight',value:100,date:'2026-01-01'}],labs:[{id:'l1',profileId:'p1',name:'Глюкоза',value:90,unit:'mg/dL',date:'2026-02-01',laboratory:'Lab A'}],sleep:[],activity:[],training:[],nutrition:[],medications:[],supplements:[],symptoms:[],goals:[],notes:[],settings:{theme:'dark'}};}
function sleepState(id='p1',duration=6){const data=emptyState();data.profiles=[{id,name:'A',primaryGoal:'сон'}];data.activeProfileId=id;for(let i=0;i<6;i++)data.sleep.push({id:`s${i}`,profileId:id,date:`2026-08-${String(i+1).padStart(2,'0')}`,duration:duration+(i%2)*.2});return data;}

test('v2 → v3 → v4 migration preserves records and validates',()=>{const v4=migrateV3ToV4(migrateV2ToV3(legacy()));assert.equal(v4.version,SCHEMA_VERSION);assert.equal(v4.labResults.length,1);assert.equal(v4.measurements.length,1);assert.equal(validateState(v4).ok,true);});
test('repository creates safety copy during v3 migration',()=>{const v3=migrateV2ToV3(legacy());const storage=new MemoryStorage({markovHealthOSData:JSON.stringify(v3)});const data=new HealthRepository(storage).load();assert.equal(data.version,4);assert.ok(storage.getItem('markovHealthOSDataSafetyBackup'));});
test('validation rejects duplicate and orphan records',()=>{const data=emptyState();data.profiles=[{id:'p1'}];data.activeProfileId='p1';data.measurements=[{id:'x',profileId:'p1'},{id:'x',profileId:'missing'}];const result=validateState(data);assert.equal(result.ok,false);assert.ok(result.errors.some(x=>x.startsWith('duplicate-id')));assert.ok(result.errors.some(x=>x.includes('orphan')));});
test('lab aliases, units and supplied references remain explicit',()=>{assert.equal(findAnalyte('ТТГ')?.id,'tsh');const converted=convertValue(findAnalyte('Глюкоза'),90,'mg/dL','ммоль/л');assert.equal(converted.ok,true);const row=normalizeResult({originalName:'Глюкоза',value:90,originalValue:90,originalUnit:'mg/dL',referenceLow:70,referenceHigh:99,valueType:'numeric'});assert.equal(labStatus(row).key,'range');});
test('import parsing validates before persistence',()=>{const csv=parseCsv('Показатель;Значение;Единица\nГлюкоза;90;mg/dL');assert.equal(csv.rows.length,1);assert.equal(parseLabText('Ферритин < 5 нг/мл 10-100')[0].operator,'<');assert.equal(validateUpload({name:'a.exe',type:'application/pdf',size:100},'pdf').ok,false);});
test('recommendations are deterministic, ranked and explainable',()=>{const data=sleepState();const first=analyze(data,'p1',{now:new Date('2026-08-12T00:00:00Z')});const second=analyze(data,'p1',{now:new Date('2026-08-12T00:00:00Z')});assert.deepEqual(first,second);assert.ok(first[0].ruleId);assert.ok(first[0].facts.length);assert.ok(first[0].priority>=0&&first[0].priority<=100);assert.ok(first[0].source.url);});
test('personalization changes output when sleep changes',()=>{const poor=sleepState('p1',5.5);const good=sleepState('p1',8);assert.notDeepEqual(getTopRecommendations(poor,'p1').top.map(x=>x.ruleId),getTopRecommendations(good,'p1').top.map(x=>x.ruleId));});
test('profiles are isolated in recommendation engine',()=>{const data=sleepState('a',5.5);data.profiles.push({id:'b',name:'B'});data.sleep.push({id:'other',profileId:'b',date:'2026-08-01',duration:9});assert.ok(analyze(data,'a').every(x=>x.facts.every(f=>!String(f).includes('other'))));});
test('personality scoring is dimensional and archetype is derived',()=>{const traits=scoreBigFive([{trait:'openness',value:5},{trait:'openness',value:4},{trait:'conscientiousness',value:2}]);assert.equal(traits.openness,4.5);assert.equal(deriveArchetype(traits).id,'openness');});
test('encrypted backup roundtrip and tamper detection',async()=>{const payload={application:'MARKOV_HEALTH_OS',data:{version:4,x:1}};const box=await encryptBackup(payload,'strong-pass-123');assert.deepEqual(await decryptBackup(box,'strong-pass-123'),payload);const storage=new MemoryStorage();const repo=new HealthRepository(storage);repo.load();const backup=await repo.exportBackupWithChecksum();assert.equal((await verifyBackupChecksum(backup)).ok,true);backup.data.version=99;assert.equal((await verifyBackupChecksum(backup)).ok,false);});
test('production entrypoint has no external request or provider import',async()=>{const {readFile}=await import('node:fs/promises');const main=await readFile(new URL('../src/app/main.js',import.meta.url),'utf8');assert.doesNotMatch(main,/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|sendBeacon/);assert.doesNotMatch(main,/openai|anthropic|gemini|chatgpt/i);});
