export const RULE_VERSION='1.0.0';
export const SOURCES=Object.freeze({
  sleepGuidance:{id:'sleep.guidance',title:'Adult sleep duration guidance',organization:'CDC',year:2024,url:'https://www.cdc.gov/sleep/about_sleep/how_much_sleep.html',grade:'Strong',notes:'General population guidance; not an individual diagnosis.'},
  activityGuidance:{id:'activity.guidance',title:'Physical activity recommendations',organization:'WHO',year:2020,url:'https://www.who.int/publications/i/item/9789240015128',grade:'Strong',notes:'Use as broad context, not a mandatory target.'},
  habitFormation:{id:'habit.formation',title:'Habit formation in real life',organization:'European Journal of Social Psychology',year:2009,url:'https://doi.org/10.1002/ejsp.674',grade:'Moderate',notes:'Formation time varies widely by behaviour and person.'},
  personality:{id:'personality.big-five',title:'Five-Factor Model overview',organization:'APA Dictionary',year:2024,url:'https://dictionary.apa.org/big-five-model',grade:'Moderate',notes:'Dimensional description; no diagnosis or fixed type.'}
});

export const RULES=Object.freeze([
  {id:'sleep.duration.low',domain:'sleep',source:'sleepGuidance',evidence:'Strong',impact:82,actionability:86,burden:28,
    when:s=>s.sleep.sampleSize>=3&&s.sleep.averageDuration<7,
    build:(s,p)=>({title:'Увеличить окно сна',observation:`Средняя длительность сна — ${s.sleep.averageDuration.toFixed(1)} ч за ${s.sleep.sampleSize} записей.`,explanation:'Недостаточная длительность сна может ухудшать восстановление, внимание и устойчивость режима; система не делает медицинский вывод.',recommendation:'Добавьте 30 минут к окну сна на ближайшие 7 дней и отметьте энергию утром.',nextCheck:'Пересчитать после 7 новых ночей.',facts:[`averageDuration=${s.sleep.averageDuration.toFixed(2)}`,`sampleSize=${s.sleep.sampleSize}`],goalDomains:['health','sleep','energy'],expectedBenefit:'восстановление и дневная энергия',effort:32,cost:0})},
  {id:'sleep.regularity.high_variance',domain:'sleep',source:'sleepGuidance',evidence:'Moderate',impact:70,actionability:78,burden:22,
    when:s=>s.sleep.sampleSize>=4&&s.sleep.durationVariance>0.9,
    build:(s)=>({title:'Стабилизировать время подъёма',observation:`Разброс длительности сна — ${s.sleep.durationVariance.toFixed(1)} ч.`,explanation:'Большая вариативность делает среднее менее полезным и может мешать устойчивому ритму.',recommendation:'Зафиксируйте время подъёма в пределах ±30 минут хотя бы 5 дней.',nextCheck:'Проверить вариативность через 14 дней.',facts:[`durationVariance=${s.sleep.durationVariance.toFixed(2)}`],goalDomains:['sleep','energy'],expectedBenefit:'предсказуемость режима',effort:24,cost:0})},
  {id:'training.recovery.mismatch',domain:'training',source:'sleepGuidance',evidence:'Moderate',impact:76,actionability:73,burden:34,
    when:s=>s.training.sampleSize>=3&&s.training.load>120&&s.sleep.sampleSize>=3&&s.sleep.averageDuration<7,
    build:(s)=>({title:'Снизить нагрузку на неделю',observation:`Нагрузка тренировок высокая (${Math.round(s.training.load)} усл. ед.), а сон ниже 7 ч.`,explanation:'Сочетание высокой нагрузки и короткого сна — повод временно уменьшить объём и проверить восстановление, не диагноз перетренированности.',recommendation:'Сократите объём ближайшей тренировки на 20–30% или добавьте день лёгкой активности.',nextCheck:'Сверить сон, энергию и RPE после следующей недели.',facts:[`trainingLoad=${Math.round(s.training.load)}`,`averageSleep=${s.sleep.averageDuration.toFixed(1)}`],goalDomains:['training','recovery'],expectedBenefit:'восстановление и соблюдаемость плана',effort:48,cost:0})},
  {id:'body.weight.trend',domain:'body',source:'activityGuidance',evidence:'Limited',impact:62,actionability:74,burden:18,
    when:(s,p)=>p?.primaryGoal?.toLowerCase().includes('вес')&&s.body.sampleSize>=3&&s.body.slope>0.12,
    build:(s)=>({title:'Проверить тренд массы, а не одну точку',observation:`Последние измерения показывают положительный наклон около ${s.body.slope.toFixed(2)} кг на запись.`,explanation:'Вес колеблется из-за жидкости и условий измерения; решение лучше принимать по повторяемому тренду.',recommendation:'Измеряйте массу 3–4 раза в неделю в похожих условиях и смотрите среднее за 14 дней.',nextCheck:'Оценить среднее после 14 дней.',facts:[`weightSlope=${s.body.slope.toFixed(3)}`],goalDomains:['weight','body'],expectedBenefit:'качество обратной связи по цели',effort:20,cost:0})},
  {id:'psychology.stress.high',domain:'psychology',source:'habitFormation',evidence:'Limited',impact:72,actionability:80,burden:20,
    when:s=>s.mood.stressSample>=3&&s.mood.stress>=7,
    build:(s)=>({title:'Сделать стресс измеримым и снизить один источник',observation:`Средний стресс — ${s.mood.stress.toFixed(1)}/10 за ${s.mood.stressSample} записей.`,explanation:'Одна конкретная перемена и короткий цикл проверки обычно полезнее длинного списка советов.',recommendation:'Выберите один повторяющийся триггер и запланируйте 10-минутный буфер перед ним.',nextCheck:'Оценить стресс через 7 дней.',facts:[`stressMean=${s.mood.stress.toFixed(2)}`],goalDomains:['stress','psychology'],expectedBenefit:'контроль нагрузки',effort:26,cost:0})},
  {id:'data.coverage.sleep',domain:'system',source:'sleepGuidance',evidence:'Strong',impact:58,actionability:90,burden:12,
    when:s=>s.sleep.sampleSize<3,
    build:()=>({title:'Добавить базовые записи сна',observation:'Для сна пока недостаточно повторных записей.',explanation:'Без baseline система не может отличить разовую ночь от устойчивого паттерна.',recommendation:'Запишите длительность и субъективное качество сна ещё 4 раза.',nextCheck:'После 4 записей появятся персональные тренды.',facts:['sleepSample<3'],goalDomains:['data-quality'],expectedBenefit:'точность следующих рекомендаций',effort:18,cost:0})},
  {id:'goal.next.action',domain:'goals',source:'habitFormation',evidence:'Moderate',impact:60,actionability:88,burden:14,
    when:s=>s.goals.length>0&&s.tasks.length===0,
    build:()=>({title:'Превратить активную цель в следующий шаг',observation:'Есть активная цель, но нет задач, связанных с её выполнением.',explanation:'Цель без ближайшего действия не создаёт обратной связи и легко остаётся намерением.',recommendation:'Создайте одну задачу на 15–30 минут, связанную с ближайшим измеримым шагом.',nextCheck:'Проверить выполнение через 7 дней.',facts:['activeGoals>0','tasks=0'],goalDomains:['goals','productivity'],expectedBenefit:'движение цели',effort:22,cost:0})}
]);
